# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=200)),
                ('data_matricula', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('contato', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=200)),
                ('tipo_pagamento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('cod_Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eape.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('diasDaSemana', models.CharField(choices=[('SegundaQuarta', 'Segunda e Quarta'), ('TercaQuinta', 'Terça e Quinta'), ('Sexta', 'Sexta'), ('Sabado', 'Sabado')], max_length=200)),
                ('turno', models.CharField(choices=[('Manha', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=100)),
                ('horario', models.TimeField(blank=True, verbose_name='Turma Time')),
                ('cod_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eape.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=75)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='cod_Turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eape.Turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cod_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eape.Turma'),
        ),
    ]
