# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eape', '0004_auto_20170825_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
