# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eape', '0009_frequencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='turma',
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
    ]
