# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eape', '0013_frequencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='aluno',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ManyToManyField(to='eape.Aluno'),
        ),
    ]
