# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eape', '0014_auto_20170825_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencia',
            old_name='aluno',
            new_name='alunos',
        ),
    ]
